language: java
script: mvn clean install -Ptravis
# Remove --quiet to avoid timeouts
install: mvn install -DskipTests=true

notifications:
  email:
    - ri-dev@ning.com

jdk:
  - openjdk6
  - openjdk7
  - oraclejdk7

env:
  - MAVEN_OPTS="-Xmx512m -XX:MaxPermSize=192m"
